/**
 * @file docxService.ts
 * @description Service for generating and downloading Microsoft Word (.docx) documents 
 * from the generated didactic sequences. Uses the 'docx' and 'file-saver' libraries.
 */

import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, HeadingLevel, AlignmentType, ExternalHyperlink } from "docx";
import { saveAs } from "file-saver";
import { DidacticSequence, SequenceInput } from "../types";

/**
 * Generates a formal .docx document based on the AI response.
 * Includes tables for general info, activities, and rubrics.
 * 
 * @param data The didactic sequence generated by the AI
 * @param input The original user inputs for context
 */
export const generateDocx = async (data: DidacticSequence, input: SequenceInput) => {

  /**
    * Internal helper to create a consistent two-column row for tables.
    * @param label Left column text (bold)
    * @param value Right column text
    */
  const createRow = (label: string, value: string) => {
    return new TableRow({
      children: [
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })],
        }),
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun(value || "")] })],
        }),
      ],
    });
  };

  // --- Activities Table Processing ---
  const activitiesRows = data.actividades.flatMap((act) => {
    const rows = [
      new TableRow({
        children: [
          new TableCell({
            columnSpan: 2,
            children: [
              new Paragraph({
                children: [new TextRun({ text: `Sesión ${act.sesion} (${act.tiempo || '60 min'})`, bold: true })],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        ],
      }),
    ];

    if (act.fase_inicio) rows.push(createRow("Fase de Inicio (Exploración)", act.fase_inicio));
    if (act.fase_desarrollo) rows.push(createRow("Fase de Desarrollo (Estructuración)", act.fase_desarrollo));
    if (act.fase_cierre) rows.push(createRow("Fase de Cierre (Transferencia)", act.fase_cierre));
    if (act.descripcion && !act.fase_inicio) rows.push(createRow("Descripción", act.descripcion));
    
    if (act.preguntas_socraticas) {
      const qs = Array.isArray(act.preguntas_socraticas) ? act.preguntas_socraticas.join(" | ") : String(act.preguntas_socraticas);
      if (qs.trim().length > 0) rows.push(createRow("Preguntas Socráticas", qs));
    }
    if (act.adi_especifico) rows.push(createRow("Momento ADI / Corporiedad", act.adi_especifico));
    if (act.materiales) {
      const mats = Array.isArray(act.materiales) ? act.materiales.join(", ") : String(act.materiales);
      if (mats.trim().length > 0) rows.push(createRow("Materiales", mats));
    }
    if (act.imprimibles) rows.push(createRow("Imprimibles / Recursos", act.imprimibles));

    return rows;
  });

  // --- Rubric Table Processing ---
  const rubricRows = [
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Criterio", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Bajo", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Básico", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Alto", bold: true })] })] }),
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Superior", bold: true })] })] }),
      ]
    }),
    ...data.rubrica.map(r => new TableRow({
      children: [
        new TableCell({ children: [new Paragraph(r.criterio || "")] }),
        new TableCell({ children: [new Paragraph(r.bajo || (r.criterio ? `Demuestra dificultades iniciales en ${r.criterio.toLowerCase()} y requiere apoyo.` : "Desempeño bajo con necesidades de refuerzo."))] }),
        new TableCell({ children: [new Paragraph(r.basico || "")] }),
        new TableCell({ children: [new Paragraph(r.alto || r.satisfactorio || "")] }),
        new TableCell({ children: [new Paragraph(r.superior || r.avanzado || "")] }),
      ]
    }))
  ];

  // --- Evaluation paragraphs (ICFES complete) ---
  const evaluacionParagraphs = data.evaluacion.flatMap((item, i) => {
    const pList: Paragraph[] = [
      new Paragraph({
        children: [new TextRun({ text: `Pregunta ${i + 1}: ${item.pregunta}`, bold: true })],
        spacing: { before: 200, after: 100 }
      })
    ];

    if (item.opciones && item.opciones.length > 0) {
      item.opciones.forEach(op => {
        pList.push(new Paragraph({
          children: [new TextRun(`  ${op}`)],
          spacing: { after: 50 }
        }));
      });
    }

    if (item.respuesta_correcta) {
      pList.push(new Paragraph({
        children: [
          new TextRun({ text: "Clave / Respuesta: ", bold: true }),
          new TextRun(item.respuesta_correcta)
        ],
        spacing: { before: 50, after: 50 }
      }));
    }

    if (item.justificacion) {
      pList.push(new Paragraph({
        children: [
          new TextRun({ text: "Justificación Pedagógica: ", italics: true }),
          new TextRun(item.justificacion)
        ],
        spacing: { after: 150 }
      }));
    }

    return pList;
  });

  // --- Document Assembly ---
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Header
          new Paragraph({
            text: "INSTITUCIÓN EDUCATIVA GUAIMARAL",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "FORMATO DE SECUENCIA DIDÁCTICA INSTITUCIONAL",
            heading: HeadingLevel.HEADING_2,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "" }), // Spacer

          // Administrative Info Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              createRow("Título Secuencia", data.titulo_secuencia || input.tema),
              createRow("Grado", input.grado),
              createRow("Área", input.area),
              createRow("Tema", input.tema),
              createRow("DBA Oficial", data.dba_utilizado || input.dba),
              createRow("Eje Transversal (CRESE)", data.eje_crese_utilizado || input.ejeCrese),
              createRow("Objetivo de Aprendizaje", data.objetivo_aprendizaje),
              createRow("Estándar MEN", data.estandar),
              createRow("Competencias MEN", data.competencias_men),
              createRow("Metodología", data.metodologia),
              createRow("Corporiedad / Momento ADI", data.corporiedad_adi),
              createRow("Productos Asociados", data.productos_asociados),
              createRow("Instrumentos de Evaluación", data.instrumentos_evaluacion),
              createRow("Adecuaciones PIAR (Inclusión)", data.adecuaciones_piar),
              createRow("Bibliografía", data.bibliografia),
              createRow("Observaciones", data.observaciones),
            ],
          }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "DESGLOSE DETALLADO DE SESIONES", heading: HeadingLevel.HEADING_3 }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: activitiesRows,
          }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "RÚBRICA DE EVALUACIÓN (DECRETO 1290)", heading: HeadingLevel.HEADING_3 }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: rubricRows
          }),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "EVALUACIÓN Y SIMULACRO SABER-ICFES", heading: HeadingLevel.HEADING_3 }),
          ...evaluacionParagraphs,

          new Paragraph({ text: "" }),
          new Paragraph({ text: "TALLER DE APLICACIÓN IMPRIMIBLE", heading: HeadingLevel.HEADING_3 }),
          new Paragraph({ children: [new TextRun({ text: data.taller_imprimible?.introduccion || "", italics: true })] }),
          new Paragraph({ children: [new TextRun({ text: "Instrucciones:", bold: true })] }),
          new Paragraph({ text: data.taller_imprimible?.instrucciones || "" }),
          new Paragraph({ children: [new TextRun({ text: "Ejercicios:", bold: true })] }),
          ...(data.taller_imprimible?.ejercicios || []).map((ej, i) => new Paragraph({
            children: [new TextRun(`${i + 1}. ${ej}`)],
            spacing: { before: 100, after: 100 }
          })),
          new Paragraph({ text: "" }),
          new Paragraph({ children: [new TextRun({ text: "RETO CREATIVO:", bold: true })] }),
          new Paragraph({ children: [new TextRun({ text: data.taller_imprimible?.reto_creativo || "", italics: true })] }),

          ...(data.glosario && data.glosario.length > 0 ? [
            new Paragraph({ text: "" }),
            new Paragraph({ text: "GLOSARIO DE TÉRMINOS CLAVE", heading: HeadingLevel.HEADING_3 }),
            ...data.glosario.map(g => new Paragraph({
              children: [
                new TextRun({ text: `• ${g.termino}: `, bold: true }),
                new TextRun(g.definicion)
              ]
            }))
          ] : []),

          ...(data.aula_invertida ? [
            new Paragraph({ text: "" }),
            new Paragraph({ text: "AULA INVERTIDA (FLIPPED CLASSROOM)", heading: HeadingLevel.HEADING_3 }),
            new Paragraph({ text: data.aula_invertida })
          ] : []),

          new Paragraph({ text: "" }),
          new Paragraph({ text: "RECURSOS Y MATERIALES MULTIMEDIA", heading: HeadingLevel.HEADING_3 }),
          ...(data.recursos || []).map(r => {
            const textToSearch = `${r.nombre} ${r.descripcion}`;
            const urlMatch = textToSearch.match(/(https?:\/\/[^\s]+)/);
            const foundUrl = urlMatch ? urlMatch[0] : null;

            const isVideo = r.nombre.toLowerCase().includes("video") || r.descripcion.toLowerCase().includes("video") || r.nombre.toLowerCase().includes("youtube");
            const rawTitle = r.nombre.replace(/^video\s*[:-]?\s*/i, "").replace(/['"]/g, "").trim();
            const searchQuery = rawTitle ? `${rawTitle} ${data.tema_principal || input.tema}` : `explicacion ${data.tema_principal || input.tema}`;
            
            const targetUrl = foundUrl || (
              isVideo 
                ? `https://www.youtube.com/results?search_query=${encodeURIComponent(searchQuery)}`
                : `https://www.google.com/search?q=${encodeURIComponent(`${rawTitle || r.nombre} ${data.tema_principal || input.tema}`)}`
            );

            return new Paragraph({
              children: [
                new TextRun({ text: `• ${r.nombre}: `, bold: true }),
                new TextRun(r.descripcion + " "),
                new ExternalHyperlink({
                  children: [
                    new TextRun({
                      text: isVideo ? "[▶ Ver Video en YouTube]" : "[🌐 Abrir Recurso en Web]",
                      color: "0066CC",
                      underline: {},
                    }),
                  ],
                  link: targetUrl,
                }),
              ],
              spacing: { before: 80, after: 80 }
            });
          })
        ],
      },
    ],
  });

  // Pack and Save
  const blob = await Packer.toBlob(doc);
  const fileName = `Secuencia_${input.tema.replace(/\s+/g, '_')}_${input.grado.replace(/\s+/g, '_')}.docx`;
  saveAs(blob, fileName);
};
